#!/usr/bin/env bash

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)

if [ -n "$BRANCH_NAME" ] && [ "$BRANCH_NAME" != "HEAD" ]; then
    PREFIX_PATTERN='[A-Z]{2,5}-[0-9]{1,4}'
    [[ $BRANCH_NAME =~ $PREFIX_PATTERN ]]
    PREFIX=${BASH_REMATCH[0]}
    PREFIX_IN_COMMIT=$(grep -c "$PREFIX:" "$1")
    if [[ -n "$PREFIX" ]] && ! [[ $PREFIX_IN_COMMIT -ge 1 ]]; then
        sed -i.bak -e "1s~^~$PREFIX: ~" "$1"
    fi
fi
